language: node_js
cache: npm
node_js:
- '8'
- '10'
- '12'
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: jessec.cameron@gmail.com
  api_key:
    secure: Zvjkk785nWXvN/n+uz3SR9tSiOJpKM/oycQlExdYx5Go5rndYQNUZbg279JV4M54OaUsnc/uLP18MiX3bYSWwMaVYtDQiq8OSJvzWNYD/7gnqZFzhabVQbdZtdQ8uc2i4sQAXkXqIqadOeN9X+l2UwaBFKfU+QIczhPL7gvEgkeDw9zqwYD23IWpg5DRqSsw+VJEW55aNyY8oEUNP4H/+W1NcvWDN3xcSRGazmRPIPXrfwe+NIk6RtcZQKr/8/ui3oNCZr9dY5W9CgvBwMrkuXhLxcObXY3K9u1JaOm09LQeSLRUlB5JQRIdFvuhxSC4y9GzFSh0E6uPD/p3vnXjFwyKfpoL9qTxVhNmpnOi/UJVQIoNHCABzK55CQlbCMkpMvCivzDx4WN5MktmK777pgx2w0fS6vIdFvAanYjrB/a2Wb5eLEa8mpSxsd68RxwyesRUbuQCTPp0/lZT+rhRYiYnmEuimwqCaxpltO4+O4h04mX7caBNFzswFq049cDmqvuXe+6qiS409gmP9oiLiY5KnDppVD1P2/1/opBkLG5yM+KQDGN6YCx39xbuhhUagYmXfxp4Zaco1s7Z0VboKrUSQqRni7cR/NxLoSLcQkxAvluUvqG6jOFwE4qYbNDDUd9JFfwl8+EcwJlF3474BtXTOH0LoLfz/d9BT/pUaO4=
  on:
    tags: true
    repo: Jesse-Cameron/p-truthy-race
